#!/bin/sh

stop(){
state=`docker inspect --format {{.State.Running}} "${NAME}" 2>/dev/null`
	if [ "$state" == "true" ]; then
		printf "Stop: "
		docker stop "${NAME}"
		printf "Remove: "
		docker rm "${NAME}"
	elif [ "$state" == "false" ]; then
		printf "Stop: "
		docker rm "${NAME}";
	fi
}

run(){
	printf "Run: " && \
	docker run -h ${NAME} \
	-it \
	-d \
	--name ${NAME} \
	--privileged \
    -e MYUSER=stephen \
    -v inside-var-lib:/var/lib \
    -v inside-var-lib-docker:/var/lib/docker \
	-v inside-home:/home \
	${TAG}
}


. env && \
./build && \
stop && \
run

